spring.application.name=Biblio
server.port=8081

# H2 DATABASE - File-based (persistent)
spring.datasource.url=jdbc:h2:file:./data/biblio
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true