spring.application.name=Biblio

# SERVER (IMPORTANT FOR RENDER)
server.port=${PORT:8080}

# DATABASE (temporary option for deploy testing)
spring.datasource.url=jdbc:h2:mem:biblio
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# DISABLE H2 CONSOLE (production safe)
spring.h2.console.enabled=false

# OPTIONAL
spring.jpa.defer-datasource-initialization=true